kubectl delete -f kafka-service.yaml
kubectl delete -f kafka-rc.yaml
kubectl delete -f zookeeper.yaml
kubectl delete -f zk-pvc.yaml
kubectl delete -f kafka-pvc.yaml
kubectl delete -f kafka-pv.yaml
kubectl delete -f zk-pv.yaml
kubectl delete pod kafka-broker-0
kubectl delete pod kafka-broker-1
kubectl delete pod kafka-broker-2
kubectl delete pod zoo-0
kubectl delete pod zoo-1
kubectl delete pod zoo-2
