apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: kafka-broker
spec:
  serviceName: kafka-service
  replicas: 3
  #selector:
  #  app: kafka
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk:2181
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:2:1,order-book-updates:1:1
        volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim: 
              claimName: kafkaclaim
